export const LOGIN_SUCCESS = 'login_success'
export const REGISTER_SUCCESS = 'register_success'
export const AUTH_ERROR = 'auth_error'
export const AUTH_LOADING = 'auth_loading'
export const CLEAR_AUTH_ERROR = 'clear_auth_error'
export const CLEAR_AUTH_SUCCESS = 'clear_auth_success'
export const LOG_OUT = 'log_out'

export const USER_LOADING = 'user_loading'
export const SET_CURRENT_USER = 'set_current_user'
export const USER_ERROR = 'user_error'
export const ADD_FOLLOWING = 'add_following'
export const REMOVE_FOLLOWING = 'remove_following'
export const CLEAR_USER_ERROR = 'clear_user_error'
export const CLEAR_USER_SUCCESS = 'clear_user_success'


export const POST_LOADING = 'post_loading'
export const SET_POSTS = 'set_posts'
export const POST_ERROR = 'post_error'
export const ADD_POST = 'add_post'
export const REMOVE_POST = 'remove_post'
export const ADD_LIKE = 'add_like'
export const REMOVE_LIKE = 'remove_like'
export const CLEAR_POST_ERROR = 'clear_post_error'
export const CLEAR_POST_SUCCESS = 'clear_post_success'

export const COMMENT_LOADING = 'comment_loading'
export const SET_COMMENTS = 'set_comments'
export const COMMENT_ERROR = 'comment_error'
export const ADD_COMMENT = 'add_comment'
export const REMOVE_COMMENT = 'remove_comment'
export const CLEAR_COMMENT_ERROR = 'clear_comment_error'
export const CLEAR_COMMENT_SUCCESS = 'clear_comment_success'

export const SEARCH_LOADING = 'search_loading'
export const SEARCH_ERROR = 'search_error'
export const SET_SEARCH_USERS = 'set_search_users'
export const CLEAR_SEARCH_ERROR = 'clear_search_error'
export const CLEAR_SEARCH_SUCCESS = 'clear_search_success'

